export const IPC_CHANNELS = {
  app: {
    getInfo: "assetwell:app:get-info",
    getCurrentReleaseNotes: "assetwell:app:get-current-release-notes",
  },
  higgsfield: {
    getStatus: "assetwell:higgsfield:get-status",
    signIn: "assetwell:higgsfield:sign-in",
    checkCredits: "assetwell:higgsfield:check-credits",
    checkWorkspace: "assetwell:higgsfield:check-workspace",
    listModels: "assetwell:higgsfield:list-models",
    getModelDetails: "assetwell:higgsfield:get-model-details",
    chooseAsset: "assetwell:higgsfield:choose-asset",
    uploadAsset: "assetwell:higgsfield:upload-asset",
    generate: "assetwell:higgsfield:generate",
    openOutput: "assetwell:higgsfield:open-output",
    cancelCommand: "assetwell:higgsfield:cancel-command",
    commandOutput: "assetwell:higgsfield:command-output",
  },
  library: {
    loadSnapshot: "assetwell:library:load-snapshot",
    saveSnapshot: "assetwell:library:save-snapshot",
    getSettings: "assetwell:library:get-settings",
    chooseOutputRoot: "assetwell:library:choose-output-root",
    revealOutputRoot: "assetwell:library:reveal-output-root",
    loadUploadsSnapshot: "assetwell:library:load-uploads-snapshot",
    setActiveUploadWorkspace: "assetwell:library:set-active-upload-workspace",
    createUploadWorkspace: "assetwell:library:create-upload-workspace",
    updateUploadWorkspace: "assetwell:library:update-upload-workspace",
    deleteUploadWorkspace: "assetwell:library:delete-upload-workspace",
    importReferenceAssets: "assetwell:library:import-reference-assets",
    revealReferenceAssets: "assetwell:library:reveal-reference-assets",
    deleteReferenceAsset: "assetwell:library:delete-reference-asset",
    exportCreativeZip: "assetwell:library:export-creative-zip",
    exportVideo: "assetwell:library:export-video",
  },
  updater: {
    getDownloadedUpdate: "assetwell:updater:get-downloaded-update",
    installDownloadedUpdate: "assetwell:updater:install-downloaded-update",
    downloadedUpdate: "assetwell:updater:downloaded-update",
  },
} as const
